'use strict';
const M=TaskModel, TODAY=M.key(new Date()), STORE='TaskYUL.v4';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>globalThis.crypto?.randomUUID?.()||('id'+Date.now()+Math.random().toString(36).slice(2));

function seed(){return {version:4,tasks:[],projects:[{id:'Личные',name:'Личные',client:'',contacts:'',notes:''}],habits:[{id:'speech',title:'Речь',detail:'15 минут ежедневно',weekly:7},{id:'english',title:'Английский',detail:'5 раз в неделю',weekly:5},{id:'training',title:'Тренировка',detail:'Ежедневно',weekly:7},{id:'other',title:'Что-то другое',detail:'Ежедневно',weekly:7}],marks:{},files:[]}}
let db;try{db=JSON.parse(localStorage.getItem(STORE))||seed()}catch(e){db=seed()}
let ui={view:'home',project:null,calendarMode:'day',calendarDate:TODAY,miniDate:TODAY,habitMode:'week',habitDate:TODAY,habitChartMode:'week',habitChartDate:TODAY,taskChartMode:'week',taskChartDate:TODAY,showDone:false,taskFilter:'all',taskDate:TODAY,urgency:'all'};
const views={home:'Обзор',calendar:'Календарь',projects:'Проекты',habits:'Привычки'};
let toastTimer;
function toast(msg){$('#toast').textContent=msg;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4000)}
function persist(){try{localStorage.setItem(STORE,JSON.stringify(db));return true}catch(e){toast('Не удалось сохранить данные: проверьте свободное место в браузере.');return false}}
function fmt(s,options={day:'numeric',month:'short'}){return M.date(s).toLocaleDateString('ru-RU',options)}
function spanLabel(s,mode){const ds=M.period(s,mode);return mode==='month'?fmt(s,{month:'long',year:'numeric'}):mode==='day'?fmt(s,{day:'numeric',month:'long',year:'numeric'}):`${fmt(ds[0])} — ${fmt(ds.at(-1))}`}
function segments(action,entries,value,extra=''){return `<div class="segments ${action==='priority'?'priority':''}" role="group">${entries.map(([v,l])=>`<button data-action="${action}" data-value="${v}" ${extra} class="${v===value?'selected':''}" aria-pressed="${v===value}">${l}</button>`).join('')}</div>`}
const periods=[['day','День'],['week','Неделя'],['month','Месяц']];
function navigation(scope,mode,date){return `<div class="date-nav"><button data-action="prev" data-scope="${scope}" aria-label="Предыдущий период">‹</button><b>${spanLabel(date,mode)}</b><button data-action="next" data-scope="${scope}" aria-label="Следующий период">›</button><button data-action="now" data-scope="${scope}">Сегодня</button></div>`}
function taskCheck(t){return `<input type="checkbox" data-task="${esc(t.id)}" ${t.done?'checked':''} aria-label="Выполнено: ${esc(t.title)}">`}
function due(t){if(!t.date)return 'Без срока';if(t.dueType==='week')return 'Неделя до '+fmt(t.date);return fmt(t.date)+(t.time?` · ${t.time}${t.endTime?'–'+t.endTime:''}`:'')}
function urgencyColor(t){if(!t.watch||!t.date||t.done)return '';let delta=(M.date(t.date)-M.date(TODAY))/86400000;return delta<=1?'#ff9292':delta<=3?'#ffb271':delta<=7?'#e9cd85':'#80c4fa'}
function taskTable(tasks){tasks=tasks.filter(t=>ui.showDone?t.done:!t.done).sort((a,b)=>({urgent:0,high:1,normal:2}[a.priority]??2)-({urgent:0,high:1,normal:2}[b.priority]??2)||(a.date||'9999').localeCompare(b.date||'9999'));if(!tasks.length)return '<div class="empty">В этом периоде задач нет.</div>';return `<div class="table-wrap"><table class="tasks-table"><thead><tr><th></th><th>Задача</th><th>Срок</th><th>Срочность</th></tr></thead><tbody>${tasks.map(t=>`<tr><td class="check-cell">${taskCheck(t)}</td><td class="task-name-cell"><button class="task-title ${t.done?'completed':''}" data-action="edit-task" data-id="${esc(t.id)}">${esc(t.title)}</button><div class="task-meta">${esc(t.project)} · ${esc(t.owner||'Без ответственного')}</div></td><td class="deadline" style="color:${urgencyColor(t)}">${due(t)}${t.watch?' <span title="Отслеживание дедлайна">◈</span>':''}</td><td>${segments('priority',[['normal','Обычная'],['high','Важная'],['urgent','Срочно']],t.priority,`data-id="${esc(t.id)}"`)}</td></tr>`).join('')}</tbody></table></div>`}
function donut(title,subtitle,done,total,footer='Выполнено'){const pct=M.pct(done,total);return `<article class="ring-card"><div class="day-title">${esc(title)}</div><div class="date-label">${esc(subtitle)}</div><div class="donut" style="--percent:${pct}" role="img" aria-label="${esc(title)}: ${pct}%, ${done} из ${total}"><b>${pct}%</b></div><small>${footer}</small><small>${done} / ${total}</small></article>`}
function dailyRings(ds,kind){return `<div class="rings">${ds.map(d=>{const st=kind==='tasks'?M.stats(db.tasks,[d]):{done:db.habits.filter(h=>db.marks[h.id+'@'+d]).length,total:db.habits.length};return donut(fmt(d,{weekday:'long'}),fmt(d,{day:'2-digit',month:'2-digit',year:'numeric'}),st.done,st.total,'Выполнено за день')}).join('')}</div>`}
function projectSummary(p){let ts=db.tasks.filter(t=>t.project===p.name),n=ts.filter(t=>t.done).length;return{ts,n,pct:M.pct(n,ts.length)}}
function projectList(){return `<div class="project-list">${db.projects.map(p=>{const{ts,n,pct}=projectSummary(p);return `<button class="project-item" data-action="open-project" data-id="${esc(p.id)}"><span class="row"><b>${esc(p.name)}</b><small>${n}/${ts.length} · ${pct}%</small></span><div class="track"><i style="width:${pct}%"></i></div></button>`}).join('')}</div>`}
function taskAnalytics(){const ds=M.period(ui.taskChartDate,ui.taskChartMode),st=M.stats(db.tasks,ds);return `<section class="panel"><div class="section-head"><h2>Выполнение задач</h2>${segments('task-chart-mode',periods,ui.taskChartMode)}</div>${navigation('taskChart',ui.taskChartMode,ui.taskChartDate)}<p class="muted" style="margin:12px 0">${st.done} из ${st.total} · ${st.percent}% за период</p>${dailyRings(ds,'tasks')}<div class="table-wrap chart-table"><table><thead><tr><th>Дата</th><th>Задач</th><th>Готово</th><th>%</th></tr></thead><tbody>${ds.map(d=>{const x=M.stats(db.tasks,[d]);return `<tr><td>${fmt(d)}</td><td>${x.total}</td><td>${x.done}</td><td>${x.percent}%</td></tr>`}).join('')}</tbody></table></div></section>`}
function monthGrid(s,mini=false){const ds=M.period(s,'month'),offset=(M.date(ds[0]).getDay()+6)%7;return `<div class="month-grid">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="weekday">${x}</div>`).join('')}${'<span></span>'.repeat(offset)}${ds.map(d=>{const ts=db.tasks.filter(t=>t.date===d);return `<button class="month-cell ${d===TODAY?'today':''}" data-action="calendar-date" data-date="${d}" aria-label="Дела на ${fmt(d)}"><b>${M.date(d).getDate()}</b>${ts.length?`<small>${ts.length} дел</small>`:''}</button>`}).join('')}</div>`}
function home(){const total=db.tasks.length,n=db.tasks.filter(t=>t.done).length;let tasks=db.tasks.filter(t=>(ui.taskFilter==='all'||M.period(ui.taskDate,ui.taskFilter).includes(t.date)));return `<div class="stats">${[[total,'Всего задач'],[M.pct(n,total)+'%','Выполнено'],[db.tasks.filter(t=>t.priority==='urgent'&&!t.done).length,'Срочных'],[db.projects.length,'Папок проектов']].map(([v,l])=>`<div class="panel stat"><strong>${v}</strong><small>${l}</small></div>`).join('')}</div><div class="overview"><section class="panel"><div class="section-head"><h2>Все задачи</h2>${segments('task-filter',[['all','Все'],...periods],ui.taskFilter)}</div>${segments('done-filter',[['active','Активные'],['done','Выполненные']],ui.showDone?'done':'active')}<p class="muted" style="margin:10px 0">Сначала срочные, затем важные и обычные</p>${ui.taskFilter!=='all'?navigation('task',ui.taskFilter,ui.taskDate):''}${taskTable(tasks)}</section><aside class="stack"><section class="panel mini"><h2 style="margin-bottom:10px">Календарь</h2><div class="toolbar">${navigation('mini','month',ui.miniDate)}</div>${monthGrid(ui.miniDate,true)}</section><section class="panel"><div class="section-head"><h2>Проекты</h2><button data-action="nav" data-value="projects">Все →</button></div>${projectList()}</section>${taskAnalytics()}</aside></div>`}
function dayColumn(d){const ts=db.tasks.filter(t=>t.date===d&&(ui.showDone?t.done:!t.done)).sort((a,b)=>(a.time||'99').localeCompare(b.time||'99'));return `<section class="calendar-day ${d===TODAY?'today':''}"><h3>${fmt(d,{weekday:'long'})}</h3><div class="calendar-date">${fmt(d,{day:'numeric',month:'long'})}</div>${ts.length?ts.map(t=>`<div class="calendar-task">${taskCheck(t)}<button data-action="edit-task" data-id="${esc(t.id)}" style="${t.done?'text-decoration:line-through':''}">${t.time?`<b>${t.time}${t.endTime?'–'+t.endTime:''}</b><br>`:''}${esc(t.title)}<small>${esc(t.project)}${t.dueType==='week'?' · Гибкий срок до конца недели':''}</small></button></div>`).join(''):'<div class="empty">Нет дел</div>'}</section>`}
function calendar(){const ds=M.period(ui.calendarDate,ui.calendarMode);return `<section class="panel"><div class="toolbar">${segments('done-filter',[['active','Активные'],['done','Выполненные']],ui.showDone?'done':'active')}</div><div class="toolbar">${segments('calendar-mode',periods,ui.calendarMode)}<span class="spacer"></span>${navigation('calendar',ui.calendarMode,ui.calendarDate)}</div>${ui.calendarMode==='month'?monthGrid(ui.calendarDate):`<div class="calendar-grid ${ui.calendarMode==='day'?'day-mode':''}">${ds.map(dayColumn).join('')}</div>`}<p class="muted" style="margin-top:14px">Задачи без срока остаются в «Обзоре» и проектах. Нажмите название задачи, чтобы назначить дату.</p></section>`}
function urgency(){const rank={urgent:0,high:1,normal:2};const tasks=db.tasks.filter(t=>!t.done&&(ui.urgency==='all'||t.priority===ui.urgency)).sort((a,b)=>rank[a.priority]-rank[b.priority]||(a.date||'9999').localeCompare(b.date||'9999'));return `<section class="panel"><div class="section-head"><h2>Невыполненные задачи</h2>${segments('urgency-filter',[['all','Все'],['urgent','Срочно'],['high','Важные'],['normal','Обычные']],ui.urgency)}</div>${taskTable(tasks)}</section>`}
function projects(){if(ui.project)return projectDetail();return `<div class="toolbar"><h2>Мои проекты</h2><span class="spacer"></span><button class="primary" data-action="new-project">＋ Новый проект</button></div><div class="project-grid">${db.projects.map(p=>{const{ts,n,pct}=projectSummary(p);return `<button class="panel project-card" data-action="open-project" data-id="${esc(p.id)}"><h2>${esc(p.name)}</h2><small>${esc(p.client||'Заказчик не указан')}</small><div class="track"><i style="width:${pct}%"></i></div><div>${n} из ${ts.length} задач · ${pct}%</div><small>${db.files.filter(f=>f.project===p.id).length} файлов</small><p style="margin-top:16px;color:var(--orange)">Открыть проект →</p></button>`}).join('')}</div>`}
function projectDetail(){const p=db.projects.find(p=>p.id===ui.project);if(!p){ui.project=null;return projects()}const ts=db.tasks.filter(t=>t.project===p.name);const files=db.files.filter(f=>f.project===p.id);return `<div class="toolbar"><button data-action="back-projects">← Все проекты</button><h2>${esc(p.name)}</h2><span class="spacer"></span><button data-action="new-task" data-project="${esc(p.name)}">＋ Задача в проект</button></div><div class="details-grid"><div class="stack"><section class="panel"><div class="section-head"><h2>Задачи проекта</h2>${segments('done-filter',[['active','Активные'],['done','Выполненные']],ui.showDone?'done':'active')}</div>${taskTable(ts)}</section><section class="panel"><div class="section-head"><h2>Файлы (${files.length})</h2><label class="file-picker">＋ Добавить файл<input type="file" multiple data-upload="${esc(p.id)}" aria-label="Добавить файлы в проект"></label></div><p class="muted">До 200 МБ каждый. Сохраняются на этом устройстве, доступны без интернета.</p>${files.length?files.map(f=>`<div class="file-row"><div><div class="file-name">${esc(f.name)}</div><small>${fileSize(f.size)} · ${fmt(f.date)}</small></div><div class="file-actions"><button data-action="open-file" data-id="${f.id}">Открыть</button><button data-action="download-file" data-id="${f.id}">Скачать</button></div></div>`).join(''):'<div class="empty">Добавьте документы или файлы проекта.</div>'}</section></div><section class="panel"><h2 style="margin-bottom:16px">Заказчик и заметки</h2><div class="fields"><label>Заказчик<input data-project-field="client" value="${esc(p.client)}" placeholder="Имя или компания"></label><label>Контакты<input data-project-field="contacts" value="${esc(p.contacts)}" placeholder="Телефон, почта, ссылки"></label><label>Заметки<textarea data-project-field="notes" rows="12" placeholder="Бриф, договорённости, ссылки…">${esc(p.notes)}</textarea></label><span id="noteStatus" class="muted">Сохраняется автоматически</span><button data-action="save-notes">Сохранить заметки</button></div></section></div>`}
function habits(){const ds=M.period(ui.habitDate,ui.habitMode),ads=M.period(ui.habitChartDate,ui.habitChartMode);return `<div class="stack"><section class="panel"><div class="toolbar"><h2>Мои привычки</h2><span class="spacer"></span>${segments('habit-mode',periods.slice(0,2),ui.habitMode)}</div><div class="toolbar">${navigation('habit',ui.habitMode,ui.habitDate)}</div><div class="habit-grid ${ui.habitMode==='day'?'single':''}"><span></span>${ds.map(d=>`<div class="habit-date">${fmt(d,{weekday:'short'})}<br>${fmt(d,{day:'numeric',month:'numeric'})}</div>`).join('')}${db.habits.map(h=>`<div class="habit-label">${esc(h.title)}<small>${esc(h.detail)}</small></div>${ds.map(d=>`<input type="checkbox" class="habit-check" data-habit="${h.id}" data-date="${d}" ${db.marks[h.id+'@'+d]?'checked':''} aria-label="${esc(h.title)}, ${d}">`).join('')}`).join('')}</div></section><section class="panel"><div class="section-head"><h2>Графики привычек</h2>${segments('habit-chart-mode',periods.slice(1),ui.habitChartMode)}</div>${navigation('habitChart',ui.habitChartMode,ui.habitChartDate)}<div class="habit-charts">${db.habits.map(h=>{const s=M.habitStats(h,db.marks,ads);return donut(h.title,spanLabel(ui.habitChartDate,ui.habitChartMode),s.done,s.target,'Выполнений / цель')}).join('')}</div><div class="table-wrap"><table><thead><tr><th>Привычка</th><th>Выполнено</th><th>Цель</th><th>Прогресс</th></tr></thead><tbody>${db.habits.map(h=>{const s=M.habitStats(h,db.marks,ads);return `<tr><td>${esc(h.title)}</td><td>${s.done}</td><td>${s.target}</td><td>${s.percent}%</td></tr>`}).join('')}</tbody></table></div><p class="muted" style="margin:12px 0 20px">Английский: любые 5 дней в неделю. Для неполных недель месяца цель ограничена числом дней в этом месяце.</p><h3 style="margin-bottom:12px">Выполнение по каждому дню</h3>${dailyRings(ads,'habits')}</section></div>`}
function render(){document.title='TaskYUL · '+views[ui.view];$('#nav').innerHTML=Object.entries(views).map(([v,l])=>`<button data-action="nav" data-value="${v}" class="${v===ui.view?'active':''}" ${v===ui.view?'aria-current="page"':''}>${l}</button>`).join('');$('#todayLabel').textContent=fmt(TODAY,{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#pageTitle').textContent=ui.view==='home'?'Добрый день, Никита':views[ui.view];$('#content').innerHTML=({home,calendar,urgent:urgency,projects,habits}[ui.view])()}
function changePeriod(scope,dir){const modes={task:ui.taskFilter,mini:'month'};const mode=modes[scope]||ui[scope+'Mode'];const k=scope+'Date';if(dir===0)ui[k]=TODAY;else if(mode==='month'){let d=M.date(ui[k]);ui[k]=M.key(new Date(d.getFullYear(),d.getMonth()+dir,1))}else ui[k]=M.add(ui[k],dir*(mode==='week'?7:1));if(scope==='habit')ui.habitChartDate=ui.habitDate;render()}
function openEditor(id,project){const t=db.tasks.find(t=>t.id===id)||{id:'',title:'',project:project||'Личные',owner:'Никита',priority:'normal',dueType:'date',date:TODAY,time:'',endTime:'',reminder:'',watch:false,description:''};const f=$('#taskForm');f.reset();f.elements.project.innerHTML=db.projects.map(p=>`<option>${esc(p.name)}</option>`).join('');Object.entries(t).forEach(([k,v])=>{const e=f.elements.namedItem(k);if(e){if(e.type==='checkbox')e.checked=!!v;else e.value=v??''}});$('#editorTitle').textContent=id?'Редактировать задачу':'Новая задача';$('#editor').showModal()}
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f));if(!v.title.trim())return;if(v.dueType!=='none'&&!v.date){toast('Выберите дату для срока');return}if(v.time&&v.endTime&&v.endTime<=v.time){toast('Время окончания должно быть позже начала');return}let t=db.tasks.find(t=>t.id===v.id);if(!t){t={id:uid(),done:false};db.tasks.push(t)}Object.assign(t,{title:v.title.trim(),project:v.project,owner:v.owner.trim(),priority:v.priority,dueType:v.dueType,date:v.dueType==='none'?'':v.dueType==='week'?M.add(M.week(v.date),6):v.date,time:v.time,endTime:v.endTime,reminder:v.reminder,watch:!!v.watch,description:v.description});persist();$('#editor').close();render();toast('Задача сохранена')});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,v=b.dataset.value;switch(a){case 'done-filter':ui.showDone=v==='done';render();break;case 'nav':ui.showDone=false;ui.view=v;if(v==='projects')ui.project=null;render();window.scrollTo({top:0,behavior:'instant'});break;case 'open-project':ui.view='projects';ui.showDone=false;ui.project=b.dataset.id;render();window.scrollTo({top:0,behavior:'instant'});break;case 'back-projects':ui.project=null;ui.view='projects';ui.showDone=false;render();window.scrollTo({top:0,behavior:'instant'});break;case 'new-task':openEditor('',b.dataset.project);break;case 'edit-task':openEditor(b.dataset.id);break;case 'close-editor':$('#editor').close();break;case 'close-preview':$('#preview').close();break;case 'priority':{let t=db.tasks.find(t=>t.id===b.dataset.id);t.priority=v;persist();render();break}case 'calendar-mode':ui.showDone=false;ui.calendarMode=v;ui.calendarDate=TODAY;render();break;case 'calendar-date':ui.showDone=false;ui.view='calendar';ui.calendarMode='day';ui.calendarDate=b.dataset.date;render();break;case 'habit-mode':ui.habitMode=v;if(v==='day')ui.habitDate=TODAY;render();break;case 'habit-chart-mode':ui.habitChartMode=v;render();break;case 'task-chart-mode':ui.taskChartMode=v;render();break;case 'task-filter':ui.taskFilter=v;render();break;case 'urgency-filter':ui.urgency=v;render();break;case 'prev':changePeriod(b.dataset.scope,-1);break;case 'next':changePeriod(b.dataset.scope,1);break;case 'now':changePeriod(b.dataset.scope,0);break;case 'save-notes':if(persist())toast('Заметки сохранены');break;case 'open-file':await openFile(b.dataset.id);break;case 'download-file':await downloadFile(b.dataset.id);break}});
document.addEventListener('change',e=>{const x=e.target;if(x.dataset.task){const t=db.tasks.find(t=>t.id===x.dataset.task);t.done=x.checked;t.completedAt=t.done?TODAY:null;persist();render()}if(x.dataset.habit){db.marks[x.dataset.habit+'@'+x.dataset.date]=x.checked;persist();render()}if(x.matches('[data-upload]'))uploadFiles(x.files,x.dataset.upload)});
document.addEventListener('input',e=>{const x=e.target;if(x.hasAttribute('data-project-field')){const p=db.projects.find(p=>p.id===ui.project);p[x.dataset.projectField]=x.value;if(persist())$('#noteStatus').textContent='Сохранено на этом устройстве'}});
// Files are stored as blobs in IndexedDB, never in the small text storage.
const fileDB=new Promise((resolve,reject)=>{const r=indexedDB.open('TaskYUL-files',1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});fileDB.catch(()=>{});
async function fileOp(mode,fn){const db=await fileDB;return new Promise((resolve,reject)=>{const tx=db.transaction('files',mode),request=fn(tx.objectStore('files'));let result;request.onsuccess=()=>result=request.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
function fileSize(n){return n>=1048576?(n/1048576).toFixed(1)+' МБ':Math.max(1,Math.round(n/1024))+' КБ'}
async function uploadFiles(list,project){const files=Array.from(list);if(!files.length)return;toast('Сохраняю файлы…');let n=0;for(const file of files){if(file.size>200*1024*1024){toast(file.name+': файл больше 200 МБ');continue}const id=uid();try{await fileOp('readwrite',s=>s.put({id,blob:file}));db.files.push({id,project,name:file.name,type:file.type,size:file.size,date:TODAY});if(persist())n++}catch(e){toast('Не удалось сохранить '+file.name+'. Проверьте свободное место.')}}render();if(n)toast('Сохранено файлов: '+n)}
async function getFile(id){const meta=db.files.find(f=>f.id===id),stored=await fileOp('readonly',s=>s.get(id));if(!stored?.blob)throw new Error('Файл не найден на этом устройстве');return {meta,blob:stored.blob}}
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function downloadFile(id){try{const{meta,blob}=await getFile(id);saveBlob(blob,meta.name)}catch(e){toast(e.message)}}
let previewURL;$('#preview').addEventListener('close',()=>{if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null}$('#previewBody').replaceChildren()});
async function openFile(id){try{const{meta,blob}=await getFile(id);$('#previewTitle').textContent=meta.name;const body=$('#previewBody');body.replaceChildren();if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(blob);if(/^image\/(png|jpeg|webp|gif|bmp)$/.test(meta.type)){const img=document.createElement('img');img.src=previewURL;img.alt=meta.name;body.append(img)}else if(meta.type==='application/pdf'||/\.pdf$/i.test(meta.name)){const f=document.createElement('iframe');f.src=previewURL;f.title=meta.name;body.append(f)}else if((meta.type.startsWith('text/')||/\.(txt|md|csv|json|log)$/i.test(meta.name))&&blob.size<2*1024*1024){const pre=document.createElement('pre');pre.textContent=await blob.text();body.append(pre)}else{const p=document.createElement('p');p.textContent='Этот формат открывается в отдельной программе. Скачайте оригинал и откройте его в Word или программе проекта.';body.append(p)}const a=document.createElement('a');a.href=previewURL;a.download=meta.name;a.textContent='Скачать оригинал · '+fileSize(meta.size);a.style.display='inline-block';a.style.marginTop='16px';body.append(a);$('#preview').showModal()}catch(e){toast(e.message)}}
render();
const projectDialog=document.createElement('dialog');
projectDialog.id='projectEditor';
projectDialog.innerHTML='<form id="projectForm"><div class="section-head"><h2>Новый проект</h2><button type="button" data-action="close-project-editor" aria-label="Закрыть создание проекта">✕</button></div><label>Название проекта<input name="name" required maxlength="120" placeholder="Например, Новый объект"></label><label>Заказчик<input name="client" maxlength="250" placeholder="Имя или компания"></label><label>Контакты<input name="contacts" maxlength="500" placeholder="Телефон, почта, ссылки"></label><label>Заметки<textarea name="notes" rows="4" placeholder="Бриф и договорённости"></textarea></label><p id="projectError" role="alert" class="muted"></p><div class="actions"><button type="button" data-action="close-project-editor">Отмена</button><button type="submit" class="primary">Создать проект</button></div></form>';
document.body.append(projectDialog);
document.addEventListener('click',e=>{
 const a=e.target.closest('[data-action]')?.dataset.action;
 if(a==='new-project'){$('#projectForm').reset();$('#projectError').textContent='';projectDialog.showModal();}
 if(a==='close-project-editor')projectDialog.close();
});
$('#projectForm').addEventListener('submit',e=>{
 e.preventDefault();
 const values=Object.fromEntries(new FormData(e.currentTarget)),name=values.name.trim();
 if(!name){$('#projectError').textContent='Введите название проекта.';return;}
 if(db.projects.some(p=>p.name.toLocaleLowerCase()===name.toLocaleLowerCase())){$('#projectError').textContent='Проект с таким названием уже существует.';return;}
 const p={id:uid(),name,client:values.client.trim(),contacts:values.contacts.trim(),notes:values.notes.trim()};
 db.projects.push(p);
 if(!persist()){db.projects.pop();return;}
 ui.view='projects';ui.project=p.id;window.scrollTo({top:0,behavior:'instant'});
 projectDialog.close();render();toast('Проект создан');
});

